### ISSUE TITLE
Duplicate media player notitications

### ISSUE THREAD

**Issue by littlelamp100** [AdrienPoupa/VinylMusicPlayer#443]
**Description**
Sometimes I am getting duplicates of the media player notification, and the old ones can't be cleared. It looks like I have different queues from different apps, but only one of them correctly shows what's playing. This is not a problem with the classic notification, only the modern one.

**To Reproduce**
1. Open Vinyl and start playing music
2. Check to make sure the player notification is there
3. Pause the music
4. Go to the app switcher
5. Close Vinyl
6. Reopen Vinyl
7. Start playing music again
8. Check notifications, it should have created a duplicate

**Expected behavior**
I would have expected the older media player notifications to be cleared out, or at least clearable.

**Screenshots**
![Screenshot_20210512-142903_Niagara Launcher](https://user-images.githubusercontent.com/38366547/118026375-b87d0280-b32e-11eb-8936-28628df14de2.jpg)
![Screenshot_20210512-142914_Niagara Launcher](https://user-images.githubusercontent.com/38366547/118026413-c03ca700-b32e-11eb-9ae3-395f2f804401.jpg)
![Screenshot_20210512-142918_Niagara Launcher](https://user-images.githubusercontent.com/38366547/118026414-c03ca700-b32e-11eb-9162-655d8264c21a.jpg)

**Smartphone:**
 - Device: Samsung Galaxy S20+ 5G
 - Android Version: 11
 - ROM: One UI 3.1
 - Vinyl Music Player Version: 1.2.0

**Additional context**
In order to clear the duplicates, I've found that rebooting my device helps; attempting to remove them by long pressing or swiping doesn't do anything. Also, I have a feeling that this is specifically an issue with some/all Android 11 devices due to the changes they made to the media player notifications.

**Comment by soncaokim** [comment]
That's curious.

- is this happening only with Vinyl or with other app/media player as well?
- do you have any history of using Vinyl before - i.e it starts acting like this just recently or it was the case with previous versions as well?

**Comment by littlelamp100** [comment]
- I've used various other media playing apps on this version of Android (e.g. Musicolet, Pulse, VLC) and not seen this before, I've only seen it happen with Vinyl.
- I only just started using Vinyl very recently (a couple of days ago), so I can't comment on previous versions of Vinyl or One UI. However I can test previous releases of Vinyl if you think that might help troubleshoot the issue.

**Comment by soncaokim** [comment]
Frankly I dont even recognize the notification popup in your screenshots. The OS skin is probably overriding the notification here (the 4 dots, side by side widgets, rounded play button, etc)

There is high probability that rollback to previous versions wont help. If you are comfortable with installing custom APK not vetted by G Playstore, given by a stranger on the internet, then we can think of going down this road.

**Comment by littlelamp100** [comment]
Those dots at the bottom are only there because of the duplicates, and it seems that (at least from what I can find) it looks similar on Pixel devices running A11, although I don't have any to test on. 
![2021-05-12_15-49](https://user-images.githubusercontent.com/38366547/118035885-d56b0300-b339-11eb-9123-562faedf6969.png)
I'm not sure what the rounded play button is about though. In any case, I'm certainly willing to test out custom APKs to try and troubleshoot this issue.

**Comment by soncaokim** [comment]
> similar on Pixel devices running A11,

Yup, looks like we are talking about a new Android feature here: https://android-developers.googleblog.com/2020/08/playing-nicely-with-media-controls.html?m=1

> In any case, I'm certainly willing to test out custom APKs to try and troubleshoot this issue.

Here a build of version 1.1.2, before I've made some innocent change to the notification code: https://608-115534318-gh.circle-artifacts.com/0/outputs/circleci/release/vinyl_master_4a7107cd_210512-2020-circleci-release.apk

Please uninstall and reinstall, and telle how it goes.

**Comment by littlelamp100** [comment]
Hm, that seems to have fixed it. I went through the same procedure I mentioned earlier a few times on this version and haven't gotten any duplicate players. I wonder what changed?
I'm kind of noob to github so I'll let you close this thread once you deem it fixed. Thanks for being so responsive and helpful, I appreciate it.

**Comment by soncaokim** [comment]
Now that's troubling!
I might still need your help in the future to further isolate the issue.

**Comment by soncaokim** [comment]
> I'm kind of noob to github...

Bug report with precise steps that helps reproducing the issue right away - I dont expect that on noob level 👍 

--

Can you please check if this build is any better? https://609-115534318-gh.circle-artifacts.com/0/outputs/circleci/release/vinyl_android-11-notification_070ffed7_210512-2246-circleci-release.apk

It should contain the fix, or at least a work around for now. More details in https://github.com/AdrienPoupa/VinylMusicPlayer/pull/444

**Comment by littlelamp100** [comment]
Now the duplicates are back again...
I restarted to make sure it wasn't a fluke somehow, but nope they came back again
Also I forgot to mention that I always get a "shuffle all" notification on startup, I'm not sure if that's intentional or not
Should I make a recording of all of this to show you what I mean? Maybe it'll help pinpoint what the issue is

**Comment by soncaokim** [comment]
> Now the duplicates are back again...

Even with the apk containing the fix?

**Comment by littlelamp100** [comment]
Yes, the version is 1.2.0-android-11-notification_070ffed7_210512-2246CI
I reinstalled the version of 1.1.2 that you sent me to check, and that one is still working fine

Some other things that might be helpful:
- Here's that "Shuffle all" thing, I didn't see this on 1.1.2
![Screenshot_20210512-193554_Niagara Launcher](https://user-images.githubusercontent.com/38366547/118057199-66050b80-b359-11eb-8c24-23630ba8b71b.jpg)
- If I press "play" on the notification after closing the app from the app switcher but without starting Vinyl again, the interface changes from the circular play button back to the regular interface, and the music plays for a split second and cuts out, but it doesn't make a duplicate notif (it seems like the app is trying to start up again after closing it? I think I'll make a recording in a second so you can see what I mean)

I suppose a solution for my problem would be to just use 1.1.2? However I would like to figure out what's going on here

**Comment by littlelamp100** [comment]
Hopefully this can help give some insight
https://youtu.be/SVU9J3-SNcc

**Comment by soncaokim** [comment]
Will get in touch with you via this thread. Thanks for the feedback!

**Comment by littlelamp100** [comment]
Not a problem, thanks so much for maintaining this app, it's quite wonderful

**Comment by soncaokim** [comment]
The "shuffle all" item is intended for Android Auto only (and it can be other item, depending on your library section order) - I guess these are items that are shown with the rounded button in your case.

I've made a new attempt to disable them if they are being requested from the system - can you please have a look?
https://611-115534318-gh.circle-artifacts.com/0/outputs/circleci/release/vinyl_android-11-notification_ae29fc10_210513-1659-circleci-release.apk

**Comment by littlelamp100** [comment]
That seems to have fixed the duplication issue
Now if I close the app the music player notification dismisses itself instead of sticking around like it was
Also the shuffle all did not appear on reboot this time
Just to verify the version is 1.2.0-android-11-notification_ae29fc10_210513-1659CI

**Comment by soncaokim** [comment]
> Now if I close the app the music player notification dismisses itself instead of sticking around like it was

I might revisit that behavior, but if you killed the app explicitly, that's what to be expected, no?

**Comment by littlelamp100** [comment]
> I might revisit that behavior, but if you killed the app explicitly, that's what to be expected, no?
Sorry I didn't specify, I meant to say that it _was_ the behavior I was expecting. Before if I closed the app (even if I force stopped the app in settings) the duplicates would still be there, but on this new version you sent me it no longer does that, ergo it's fixed. I haven't seen any issues with the media player in this new version, so I think it's fixed now.

**Comment by soncaokim** [comment]
@littlelamp100 I have a question: Have you noticed the following behaviour? I have it on my emulator device, just wonder if this is the case on a real one.

After launch, the now-playing notification is not shown on the first play (must pause/play for it to show up in the notif dropdown)

**Comment by littlelamp100** [comment]
I haven't noticed anything like that on my device
To check I closed it, force stopped it and reopened it
Once I started playing music, the notif popped up and I didn't have to pause/play it or anything
I wonder if this behavior is different on stock Android devices though? Perhaps Samsung has done something weird with their implementation of this new media player feature

**Comment by littlelamp100** [comment]
Just checking - you meant on the latest build you sent in this thread, correct?

**Comment by soncaokim** [comment]
> Once I started playing music, the notif popped up and I didn't have to pause/play it or anything

OK, so I will pretend that I dont see this weird behaviour, or it is linked with my slow emulation setup :-)
I'm wrapping this now, dont hesitate to go back and report further findings.

The official release will come later, there are other issues still to be tackled.

**Comment by soncaokim** [comment]
Should be fixed now
